Fix #43
browserify/node-util pull request #67
Opened 2021-12-27 16:41 UTC by salemkode

2021-12-27 18:20 UTC, ljharb requested changes

2021-12-27 18:20 UTC, ljharb commented on util.js
> +if (process && process.env && process.env.NODE_DEBUG) {
this will still error if `process` isn't defined.

and, it is *always* defined, since this is a _node_ module.

2021-12-27 18:20 UTC, ljharb commented on util.js
> +  var debugEnv = env.NODE_DEBUG;
this is broken; `env` isn't a global variable.

2021-12-28 03:30 UTC, salemkode commented
![image](https://user-images.githubusercontent.com/58360393/147525054-44669a27-c8d4-446a-821e-3efb94ab90d4.png)
Now it is work

2021-12-28 03:31 UTC, ljharb commented
`env.NODE_DEBUG` is still broken, it needs to be `process.env.NODE_DEBUG`.

2022-03-27 16:40 UTC, ljharb commented
Closing, because `process` is always defined in a node module (in node, or when bundled by a non-broken node module bundler).

2022-03-27 16:40 UTC, closed without merging